In this tutorial, we review `Mathematics` for `Machine Learning`  using `numpy` module.

In [ ]:
#load numpy
import numpy as np

Q1.  In a numpy array replace all odd position numbers with 0?

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9,10]) # declearing the array

x[::2] = 0 # looking for odd position
print(x)   # output

[ 0  2  0  4  0  6  0  8  0 10]


Q2. What is the difference between the objects np.ndarray and np.array?

Q3. What is the difference, if any, between the following statements:

In [ ]:
a = np.array ([0, 0, 0])
print(type(a))
print(a)
a = np.array ([[0 , 0, 0]])
print(type(a))
a
# Yes there is difference indeed i.e, first declread is the ONE dimentional array where as the second one is TWO dimentional array

<class 'numpy.ndarray'>
[0 0 0]
<class 'numpy.ndarray'>


array([[0, 0, 0]])

Q4. A 3 × 4 × 4 array is created with entries from 1 to 48 and having shape `(3,4,4)` 

In [ ]:
my_array = np.arange(1, 49, 1).reshape(3, 4, 4) # initially we are tasking the range and then shape of the array
my_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

Q5. Index or slice in above array to get the following:

- 20.0
- [9. 10. 11. 12]
- The 3x2 array
  
  [[5., 6.],  
   [21.,22.],  
   [37., 38.]]

Q5. How to swap two columns in a 2d numpy array?

In [ ]:
my_array = np.arange(9).reshape(3,3) # decleraing the np array
print(my_array)
my_array[:,[0, 1]] = my_array[:,[1, 0]] # swapping the preffered columns
my_array

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Q6. How to reverse the columns of a 2D array?

In [ ]:
my_array = np.arange(9).reshape(3,3)
print("before reversing the array\n",my_array)
temp = np.fliplr(my_array) # There is a inbuilt function called fliplr that can be used to reverse the coulmns
print("after reversing the columns\n",temp)


before reversing the array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
after reversing the columns
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


Q7. How to print only 3 decimal places in python numpy array?

In [ ]:
my_array = np.random.rand(3,3)
print(my_array,"\n")

np.around(my_array,3) # HEere also we have something called NPROUND  in-built function we can decised to what extent we round the given ramdom number 

[[0.08810175 0.38439004 0.56349579]
 [0.21878796 0.82620056 0.39735312]
 [0.69207556 0.50882209 0.7062638 ]] 



array([[0.088, 0.384, 0.563],
       [0.219, 0.826, 0.397],
       [0.692, 0.509, 0.706]])

Q8. How to pretty print a numpy array by suppressing the scientific notation (like `1e10`)?

Q9.  Take any two arrays and stack them horizontally?

In [ ]:
x = np.array([1,2,3,4,5])

x = np.stack((np.ones((5,1)),x),axis = 1)
#my_array = np.stack((my_array1,my_array2),axis = 1)
print(my_array)


TypeError: ignored

Q10. How to get the common items between two python numpy arrays?

In [ ]:
my_array1 = np.arange(1,10,1).reshape(3,3)
print("\n",my_array1)
my_array2 = np.arange(9).reshape(3,3)
print("\n",my_array2)

c = np.intersect1d(my_array1,my_array2) # interset1d gives the common elements between the 1d arrays and there this can be used for 2d array as well(interset2d)
print("\n",c)


 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 [1 2 3 4 5 6 7 8]


Q11. How to get the positions where elements of two arrays match?

In [ ]:
my_array1 = np.array([0, 1, 2, 3, 4, 5, 6])
my_array2 = np.array([6, 5, 4, 3, 2, 1, 6])
np.where(my_array1 == my_array2)   # where will get the indexs of the common elements in two arrrays

(array([3, 6]),)

Q12. How to compute the mean, median, standard deviation of a numpy array?

In [ ]:
my_array = np.random.rand(3,3)
print(my_array)                                       # we have direct functions to this job
print("\n mean...",my_array.mean())                   # mean
print("\n median...", np.median(my_array))            # medien
print("\n standard deviation..", my_array.std())      # standard deviation

[[0.5445504  0.00877754 0.47792094]
 [0.75542367 0.20064854 0.87347446]
 [0.51470089 0.76875904 0.31186769]]

 mean... 0.4951247954740617

 median... 0.5147008920120156

 standard deviation.. 0.2678587611500504


Q13.  How to normalize an array so the values range exactly between 0 and 1?

In [ ]:
def NormalizeData(data):
    return (data - np.min(data)) / (np.max(data) - np.min(data)) # the normal formula can do job for us


my_array1 = np.arange(9).reshape(3,3)
scaled_x = NormalizeData(my_array1)

print(scaled_x)

[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


Q14. Find the eigen-values and eigen vectors for a 3x3 matrix A?

In [ ]:
my_array1 = np.arange(1,10,1).reshape(3,3)
w, v = np.linalg.eig(my_array1)     # we are 

print("Eigen values.....\n",w)
print("Eigen vectors.....\n",v)

Eigen values.....
 [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigen vectors.....
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


Q15. Find the $\ell_2$ and $\ell_4$ norms of a vector $v=(1,2,3)$?

Q16. Generate a 3x3 matrix having real numbers from 0 to 10. Perform SVD and Cholensky decomposition.

Q16. Generate a 5x3 matrix $X$ having intergers from the set $\{1,2,3,...,50\}.$ Compute the following:
- $X^TX$
- rank of $X^TX$
- the projection of the vector $y=(1,0,1)$ on the column space of $X.$ 

Q17. Write a function `is_orthogonal`$(v1,v2, tol),$ where $v1$ and $v2$ are column vectors of the same size and $tol$ is a scalar value strictly larger than 0. The output should be 1 if the angle between $v1$ and $v2$ is within $tol$ of $\pi/2;$  and 0 otherwise. You may assume that $v1$ and $v2$ are column vectors of the same size, and that $tol$ is a positive scalar.

Q18. Find the projection of $a=(4,5,6)$ on the vector $b=(7,8,9)$?

Q19. Find the `inner product` and  `outer product` of $a=(4,5,6)$ and $b=(7,8,9)$?

Q20. 